# Generated by Django 3.2.9 on 2021-11-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211109_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='WefunderImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_id', models.IntegerField(default=0)),
                ('img_file', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='wefunder',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='upload/'),
        ),
    ]
