# Generated by Django 3.2.9 on 2021-11-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211111_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wefunder',
            old_name='project_Description',
            new_name='project_description',
        ),
        migrations.AddField(
            model_name='wefundersql',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wefunderimg',
            name='img_file',
            field=models.FileField(blank=True, upload_to='upload/'),
        ),
    ]
